spring:
  application:
    name: Reto Tecnico IDS
  datasource:
    url: jdbc:mysql://localhost:3306/starwars?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: starwars
    password: Arian1902
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
